site_name: NN-EUCLID / Hyperelasticity
site_url: https://euclid-code.github.io/

nav:
    - Home: index.md
    - Publication: publication.md
    - Example: mdfiles/Example.md
    - Code / Data: code_data.md
    - Code:
        - core/features: mdfiles/features.md
        - core/loadFemData: mdfiles/loadFemData.md
        - core/utilities: mdfiles/utilities.md
        - drivers/config: mdfiles/config.md
        - drivers/main: mdfiles/main.md
        - drivers/model: mdfiles/model.md
        - drivers/train: mdfiles/train.md
        - drivers/post_process: mdfiles/post_process.md

theme: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
